<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <LangVersion>Preview</LangVersion>
        <ApplicationIcon>Resources\appicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3296.44" />
		
		<ProjectReference Include="..\XsltEditor.Transform\XsltEditor.Transform.csproj" />
	</ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\appicon.ico" />
        <EmbeddedResource Include="Resources\Highlighting\DarkMode.xshd" />
        <EmbeddedResource Include="Resources\Highlighting\LightMode.xshd" />
        <EmbeddedResource Include="Resources\completions.xsl.json" />
    </ItemGroup>
</Project>
