<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<LangVersion>Preview</LangVersion>
	<ApplicationIcon>Resources\appicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\XsltEditor.Transform\XsltEditor.Transform.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <Resource Include="Resources\appicon.ico" />
  </ItemGroup>
</Project>
