<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\appicon.ico</ApplicationIcon>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AllowedReferenceRelatedFileExtensions>.pdb</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\completions.json" />
    <None Remove="Resources\Xshd\LightMode.xshd" />
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <Resource Include="Resources\appicon.ico" />
    <Content Include="Resources\completions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Resources\Xshd\DarkMode.xshd" />
    <EmbeddedResource Include="Resources\Xshd\LightMode.xshd" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XsltEditor.Transform\XsltEditor.Transform.csproj" />
  </ItemGroup>

</Project>
