<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\appicon.ico</ApplicationIcon>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Highlighting\DarkMode.xshd" />
    <None Remove="Resources\Highlighting\LightMode.xshd" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Highlighting\DarkMode.xshd" />
    <EmbeddedResource Include="Resources\Highlighting\LightMode.xshd" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\appicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XsltEditor.Transform\XsltEditor.Transform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Behaviors\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\completions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
