name: Build and Release

on:
  push:
    tags:
      - "xslt-editor/v*"
  workflow_dispatch:

env:
  PROJECT_PATH: src/XsltEditor/XsltEditor.csproj

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      # Build and publish for single file
      - name: Build and Publish for x64 (single file)
        shell: pwsh
        run: |
          New-Item -Path XsltEditor/bin/Release(net8.0-windows7.0)/x64 -ItemType Directory -Force
          dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false -p:PublishReadyToRun=true -p:PublishTrimmed=false -p:WindowsPackageType=None -o XsltEditor/bin/Release(net8.0-windows7.0)/x64

      - name: Zip single file artifacts
        shell: pwsh
        run: |
          Compress-Archive -Path XsltEditor/bin/Release/net8.0-windows7.0/x64/* -DestinationPath x64_single_release.zip

      # Build and publish for non-single file
      - name: Build and Publish for x64 (non-single file)
        shell: pwsh
        run: |
          New-Item -Path XsltEditor/bin/Release_non_single(net8.0-windows7.0)/x64 -ItemType Directory -Force
          dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release -r win-x64 --self-contained true -p:PublishSingleFile=false -p:DebugType=None -p:DebugSymbols=false -p:PublishReadyToRun=true -p:PublishTrimmed=false -p:WindowsPackageType=None -o XsltEditor/bin/Release_non_single(net8.0-windows7.0)/x64

      - name: Zip non-single file artifacts
        shell: pwsh
        run: |
          Compress-Archive -Path XsltEditor/bin/Release_non_single/net8.0-windows7.0//x64/* -DestinationPath x64_non_single_release.zip

      - name: Generate commit log
        id: commit_log
        run: |
          echo "commits=$(git log -1 --pretty=format:'%h %s')" >> $GITHUB_ENV

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            x64_single_release.zip
            x64_non_single_release.zip
          body: |
            ## Commits
            ${{ env.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}