name: Build and Release

on:
  push:
    tags:
      - "xslt-editor/v*"
  workflow_dispatch:

env:
  WORK_DIRECTORY: ./src/XsltEditor

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: "${{ env.WORK_DIRECTORY }}"
        run: dotnet restore "Xslt Editor.sln"

      - name: Build
        working-directory: "${{ env.WORK_DIRECTORY }}"
        run: dotnet build "Xslt Editor.sln" --configuration Release --no-restore

      - name: Publish
        working-directory: "${{ env.WORK_DIRECTORY }}"
        run: |
          dotnet publish "XsltEditor/XsltEditor.csproj" -c Release -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:EnableCompressionInSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:DebugType=None `
            -p:DebugSymbols=false `
            -p:PublishReadyToRun=true `
            -p:PublishTrimmed=false `
            -p:WindowsPackageType=None `
            -p:IncludeAllContentForSelfExtract=true `
            -o ../publish

      - name: Copy exe to release
        run: Copy-Item "publish/XsltEditor.exe" -Destination "XsltEditor.exe"

      - name: Zip Release
        run: Compress-Archive -Path "publish/*" -DestinationPath "XsltEditor-Release.zip"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            XsltEditor.exe
            XsltEditor-Release.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
